### ISSUE TITLE
Unicode characters on Windows

### ISSUE THREAD

**Issue by chisqr** [randy3k/radian#157]
I am trying to print Unicode characters in the radian terminal on Windows, but its not working. Here is the command I am using:

`r$> print('\U2190')`
`[1] "<U+2190>"`

Here is my locale:

`r$> Sys.getlocale()`
`[1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"`

I am using the iosevka font for the terminal and it has the relevant character in its character set. Also the code works inside of RGui.exe

**Comment by randy3k** [comment]
It is a known issue caused by R and I have actually reported the issue to R: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17677

R-devel has added the support of [EmitEmbeddedUTF8](https://github.com/wch/r-source/commit/b021b48411552119dab42e6a5bd81ac3eac301a6).

The issue should be resolved when the next release of R is out (I also need to patch the code in https://github.com/randy3k/rchitect)

**Comment by chisqr** [comment]
Thank you, looking forward to it!

**Comment by chisqr** [comment]
I installed the most recent version of R [3.6.3], but the Unicode characters are still not working on Windows. Do I need to change some setting to make it work ?

**Comment by randy3k** [comment]
I haven't patched rchitect yet.

**Comment by randy3k** [comment]
It seems that 3.6.3 has not yet included EmitEmbeddedUTF8.

**Comment by chisqr** [comment]
Thank you for the update. Hopefully it will be available in v4.0.0 to be released next month.

**Comment by randy3k** [comment]
I have tested the coming radian 0.4.8 with R 4.0 preview.

```
PS C:\Users\vagrant> $env:R_HOME = "C:\PROGRA~1\R\R-devel"
PS C:\Users\vagrant> radian
R Under development (unstable) (2020-03-12 r77936) -- "Unsuffered Consequences"
Platform: x86_64-w64-mingw32 (64-bit)

r$> print('\U2190')
[1] "←"

r$>

```

**Comment by chisqr** [comment]
This is awesome, thank you for fixing this. I will test when v4 of R becomes available.
